test_config = {
    "lowest_acceptable_resolution": "512x512",
    "lowest_processeable_product_count": 3,
    "max_crawl_pages": 100,
    "max_crawl_depth": 5,
    "worker_count": 8,
    "brand_dna_max_images": 100,
    "brand_dna_cluster_target": 5,
    "brand_dna_cluster_discovery_images": 20,
    "brand_dna_cluster_assignment_batch_size": 12,
    "brand_dna_palette_size": 8,
    "brand_dna_min_images_per_cluster": 2,
    "brand_dna_max_images_per_cluster": 3,
    "brand_dna_min_cluster_count": 3,
    "brand_dna_fashion_filter_strategy": "clip",
    "brand_dna_fashion_filter_model": "ViT-B-32",
    "brand_dna_fashion_filter_pretrained": "openai",
    "brand_dna_fashion_filter_threshold": 0.55,
    "brand_dna_output_dir": "outputs",
    "mongo_connection_string": "mongodb://ea_brand:ea_brand_dev@localhost:27017/?authSource=admin",
    "db_name": "ea_brand_agent_test",
    "gemini_api_key": None,
    "llm_model": "gemini-3.5-flash",
}
